services:
  backend-app:
    container_name: backend-app
    build: ./
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - db_api-network
      
  nginx:
    build: ./nginx/
    container_name: nginx-proxy
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - db_api-network
    depends_on:
      - backend-app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --email eliabedosreis@gmail.com --agree-tos --no-eff-email --force-renewal -d ${DOMAIN_NAME}

volumes:
  certbot-etc:
  certbot-var:

networks:
  db_api-network:
    external: true