services:
  backend-app:
    container_name: backend-app
    build: ./
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - db_api-network
      
  nginx:
    build: ./nginx/
    container_name: nginx-proxy
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - db_api-network
    depends_on:
      - backend-app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot webroot-path=/var/www/html --email eliabedosreis@gmail.com --agree-tos --no-eff-email --force-renewal -d ec2-3-144-254-83.us-east-2.compute.amazonaws.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/admin/node_project/views/
      o: bind

networks:
  db_api-network:
    external: true